# Generated by Django 4.0.1 on 2022-01-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
        # NAME OF THE TABLE
            name='Post',
        # TWO COLUMNS IN THE SPREADSHEET
        # COLUMN 1. 'id' 
        # COLUMN 2. 'text'
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140)),
            ],
        ),
    ]
